name = "Vanilla Augmented"
author = "GrandmasterB"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7120c0e8313f7491fd2691d51bf50c1773312e945cf08a88a2306809d4b81b7f"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
