name = "Create Basics"
author = "GrandmasterB"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3277fe62f0b2a9b5727aa153c9c11c085bf79f85507850e7355f201f7b898b5c"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
