name = "Create Immersed"
author = "GrandmasterB"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f25ffb2285060ea187b183a730a5a89f7173fb8f9f84fbf230f626bad3fcca2"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
