name = "Create Immersed"
author = "GrandmasterB"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc02dba43871309fe8a15aeb22fd8268c31f6265d15f061c3b77358db901f07c"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
