name = "Create Basics"
author = "GrandmasterB"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d82b0b1a9fe5fcb7e38e7af820cb4daf5f4137b0f2e0b2e494f30240ac64cab4"

[versions]
fabric = "0.15.1"
minecraft = "1.20.1"
